# model
model: model.point_transformer_skeleton.Model
model_args:
  num_point: 25
  num_person: 2
  in_channels: 3
model_saved_name: ''

# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /home/ankin/skeleton/data/NTU_120/ntu120/xsub/val_data_joint.npy

  label_path: /home/ankin/skeleton/data/NTU_120/ntu120/xsub/val_label.pkl
train_feeder_args:
  data_path: /home/ankin/skeleton/data/NTU_120/ntu120/xsub/train_data_joint.npy
  debug: false
  label_path: /home/ankin/skeleton/data/NTU_120/ntu120/xsub/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1

# 训练参数
weight_decay: 0.0005
step: [28, 36, 44, 52]
base_lr: 0.05

# batch size
batch_size: 40
forward_batch_size: 40
test_batch_size: 40


device:
- 1
- 0

start_epoch: 0
num_epoch: 60
eval_interval: 1
eval_start: 1

# checkpoint: ./workdir/checkpoints/checkpoint-44-fwbz16-86636.pt
# weights: ./workdir/weights/weights-44-86636.pt

amp_opt_level: 1

debug: false
optimizer_states: null
phase: train
print_log: true
save_interval: 1
save_score: true
seed: 123
nesterov: true
num_worker: 8
work_dir: ./workdir
optimizer: SGD
assume_yes: true
half: false
ignore_weights: []
log_interval: 100