# log
deep_log_tool_args:
  username: 15098144981
  password: 2312
  title: msg3d
  comments: st-trm
  dataset: NTU120-xsub-joint
  task: skeleton


# model
model: model.ST_GCN
model_args:
  num_class: 120
  channel: 3
  window_size: 300
  num_point: 25
  num_person: 2
  mask_learning: True
  use_data_bn: True
  attention: True
  only_attention: True
  tcn_attention: False
  data_normalization: True
  skip_conn: True
  weight_matrix: 2
  only_temporal_attention: True
  bn_flag: True
  attention_3: False
  kernel_temporal: 9
  more_channels: False
  double_channel: True
  drop_connect: True
  concat_original: True
  all_layers: False
  adjacency: False
  agcn: False
  dv: 0.25
  dk: 0.25
  Nh: 8
  n: 4
  dim_block1: 10
  dim_block2: 30
  dim_block3: 75
  relative: False
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  visualization: False
  graph_args:
    labeling_mode: 'spatial'
  #optical_flow: True

model_saved_name: ''

# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /home/ankin/skeleton/data/NTU/ntu120/xsub/val_data_joint.npy
  label_path: /home/ankin/skeleton/data/NTU/ntu120/xsub/val_label.pkl
train_feeder_args:
  data_path: /home/ankin/skeleton/data/NTU/ntu120/xsub/train_data_joint.npy
  debug: false
  label_path: /home/ankin/skeleton/data/NTU/ntu120/xsub/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1

# 训练参数
weight_decay: 0.0005
step: [28, 36, 44, 52]
base_lr: 0.05

# batch size
batch_size: 90
forward_batch_size: 90
test_batch_size: 90

device:
- 1
- 0

start_epoch: 0
num_epoch: 60
eval_interval: 1
eval_start: 1

# checkpoint: ./workdir/checkpoints/checkpoint-44-fwbz16-86636.pt
# weights: ./workdir/weights/weights-44-86636.pt

amp_opt_level: 1

debug: false
optimizer_states: null
phase: train
print_log: true
save_interval: 1
save_score: true
seed: 123
nesterov: true
num_worker: 8
work_dir: ./workdir
optimizer: SGD
assume_yes: true
half: false
ignore_weights: []
log_interval: 100